//
//  TaskQueue.swift
//  ConcurrencyTools
//
//  Created by Ky on 2025-05-08.
//

import Foundation



/// Allows you to run async blocks in the order in which you call them, but like a `Task`, this won't block the current context; they'll be executed later on some other `Task`
public final class TaskQueue {
    
    /// Guarantees that order-critical operations are performed in the intended order
    private let syncQueue: DispatchQueue
    
    /// Allows us to wait until the next task is ready after we've processed all of them
    private let queueProcessorLazyResumeSemaphore = Semaphore()
    
    /// The task which hosts the queue processing loop
    private let processorTask: Task<Void, Never>
    
    /// Takes care of making sure task bodies are handled properly
    private let taskManager: TaskManager
    
    
    public init() {
        syncQueue = .init(label: "Sync queue for \(Self.self) \(UUID())", qos: .userInteractive)
        taskManager = .init(syncQueue: syncQueue)
        
        processorTask = Task { [taskManager, queueProcessorLazyResumeSemaphore] in
            while !Task.isCancelled {
                if let nextTask = taskManager.pop() {
                    await nextTask()
                }
                else {
                    try? await queueProcessorLazyResumeSemaphore.wait(timeout: 3)
                }
            }
        }
    }
    
    
    deinit {
        processorTask.cancel()
    }
    
    
    
    /// The type of function which will be run in a queue
    public typealias Body = @Sendable () async -> Void
    
    
    /// Identifies tasks in the queue
    fileprivate typealias ID = QueueIdentifierManager.ID
}



public extension TaskQueue {
    
    /// Saves the given function to be executed later and immdiately returns. This is guaranteed to run _after_ all previously-enqueued tasks have run.
    ///
    /// - Attention: You **must never** call this function from within ``body``.
    ///
    /// - Parameter body: A function to be executed later on some other `Task`.
    func enqueue(_ body: @escaping Body) {
        taskManager.enqueue(body) {
            queueProcessorLazyResumeSemaphore.signal()
        }
    }
}



// MARK: - `Task` sugar

public extension Task {
    
    /// Saves the given function to be executed later and immdiately returns. This is guaranteed to run _after_ all tasks which were previously enqueued onto the given queue.
    ///
    /// - Attention: You **must never** call this function from within ``body``.
    ///
    /// - Parameter body: A function to be executed later on some other `Task`.
    static func enqueuing(into queue: inout TaskQueue, _ body: @escaping TaskQueue.Body) {
        queue.enqueue(body)
    }
}



// MARK: - ID Manager

/// Manages a queue of identifiers in a synclocked way, guaranteeing each consumer gets a unique identity.
///
/// This assumes the following usage:
/// - You request an ID to use as a key to lookup something in cache later
private final class QueueIdentifierManager: @unchecked Sendable {
    
    /// This guarntees no race conditions
    private let syncQueue: DispatchQueue
    
    /// Tracks which identifier we use next
    private var nextIdentifier: ID = 0
    
    /// Tracks which identifier we distributed last
    private var oldestUnusedIdentifier: ID = 0
    
    public init(syncQueue: DispatchQueue) {
        self.syncQueue = syncQueue
    }
    
    
    
    typealias ID = Int
}



private extension QueueIdentifierManager {
    /// Passes a new identifier to the given closure which hasn't yet been generated by this manager instance
    ///
    /// - Parameter closure: Do something with the new value
    /// - Returns: Whatever `closure` returns
    func withNewIdentifier<Value>(do closure: (ID) -> Value) -> Value {
        syncQueue.sync {
            let currentIdentifier = nextIdentifier
            nextIdentifier += 1
            return closure(currentIdentifier)
        }
    }
    
    
    /// Calls the given closure, passing the oldest unused identifier, or `nil` if all have been used
    ///
    /// - Parameters:
    ///   - closure: The closure that will be passed the ID
    ///    - id: The olest identifier which has not been given by this function, or `nil` if all identifiers have been given
    ///
    /// - Returns: Whateve `closure` returns
    func popOldestUnprocessedIdentifier<Value>(_ closure: (_ id: ID?) -> Value) -> Value {
        syncQueue.sync {
            let oldest = oldestUnusedIdentifier
            guard oldest <= nextIdentifier else {
                return closure(nil)
            }
            oldestUnusedIdentifier += 1
            return closure(oldest)
        }
    }
}



// MARK: - Task Manager

/// <#Description#>
private final class TaskManager: @unchecked Sendable {
    private var taskBodies: [ID : Body] = [:]
    private let idManager: QueueIdentifierManager
    private let syncQueue: DispatchQueue
    
    
    init(syncQueue: DispatchQueue) {
        self.syncQueue = syncQueue
        self.idManager = .init(syncQueue: syncQueue)
    }
    
    
    /// Places the given task body on the queue
    ///
    /// - Parameters:
    ///   - body:            The function to run on the task queue, after all preceding functions have completed
    ///   - afterDidEnqueue: Called once the task body has successfully been enqueued
    func enqueue(_ body: @escaping Body, afterDidEnqueue: () -> Void) {
        idManager.withNewIdentifier { id in
            taskBodies[id] = body
            afterDidEnqueue()
        }
    }
    
    
    /// Returns the oldest body from the queue which has never been returned from this function, or `nil` if the queue is empty.
    ///
    /// Calling this function removes the returned body from the queue
    func pop() -> Body? {
        idManager.popOldestUnprocessedIdentifier { id in
            guard let id else { return nil }
            let body = taskBodies.removeValue(forKey: id)
            
            if nil == body {
                let valueShouldBeThere = "Attempted to pop a value which should definitely be in the queue, but isn't"
                
                if taskBodies.isEmpty {
                    assertionFailure(valueShouldBeThere)
                }
                else {
                    assertionFailure("POSSIBLE LEAK: \(valueShouldBeThere). Also, the queue still contains \(taskBodies.count) values.")
                }
            }
            
            return body
        }
    }
    
    
    
    fileprivate typealias ID = QueueIdentifierManager.ID
    public typealias Body = TaskQueue.Body
}
